apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PasinduR97/my-app.git
    targetRevision: HEAD
    path: app-1
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/PasinduR97/my-app.git
    targetRevision: HEAD
    path: app-2
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-2

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true